repos:
  - name: di-apuntes
    title: Apuntes DI
    image: images/icon-di.png
    url: https://github.com/jgarciadeparedesh02/di-apuntes.git
    branch: main
  - name: dwec-apuntes
    title: Apuntes DWEC
    image: images/icon-dwec.png
    url: https://github.com/jgarciadeparedesh02/dwec-apuntes.git
    branch: main
    index_html: index.html
  - name: bda-apuntes
    title: Apuntes BDA
    image: images/icon-bda.png
    url: https://github.com/jgarciadeparedesh02/bda-apuntes.git
    branch: main
    index_html: index.html
element_id: multirepo
target_dir: site
repos_dir: src
index_tpl: index.tpl
extra_files:
  - styles.css
  - images/search.svg
